### ISSUE TITLE
Reduce total SRAM requirements using overlay techniques during cold boot

### ISSUE THREAD

**Issue by athoelke** [ARM-software/tf-issues#118]
At the moment all the BL images use non-overlapping RAM regions. This is not strictly necessary as not all the images need to be active concurrently. Significant reduction in total RAM requirements could be achieved by overlaying the images or their runtime memory.

This issue is to collect all the related ideas together:
- [x] <del>#75 Reclaim BL1's data memory on entry to BL2</del> Now obsolete
- [x] #81 Move TSP on FVPs from Secure DRAM to Secure SRAM
- [x] <del>#83 Free memory used by routines and data only during cold boot</del> Maybe do this later
- [x] #117 Overlay BL3-1 at the high end of SRAM 'on top' of BL2

**Comment by antonio-nino-diaz-arm** [comment]
https://github.com/ARM-software/arm-trusted-firmware/pull/1603
